#This handles all of the http request to simple cert issues and both the SP and IdP can share the same ports.
idp:
  build: ./idp-http2/
  environment:
   - JETTY_MAX_HEAP=64m
   - JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=password
   - JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=password
  ports:
   - "80:80"
   - "443:4443"
  links:
   - ldap:ldap   
 
ldap:
  build: ./ldap/
